# Generated by Django 2.0.4 on 2018-05-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCode4Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mobile_code_start', models.BigIntegerField(default=0)),
                ('mobile_code_end', models.BigIntegerField(default=0)),
                ('reservation_strategy_666', models.BooleanField(default=False)),
                ('reservation_strategy_888', models.BooleanField(default=False)),
                ('reservation_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_number', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('is_achieved', models.BooleanField(default=False)),
                ('id_reserved', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
